Merge check raw

diff --git a/.github/workflows/build_lists.yml b/.github/workflows/build_lists.yml
--- a/.github/workflows/build_lists.yml
+++ b/.github/workflows/build_lists.yml
@@ -16,11 +16,71 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
+      - name: Empty line check
+          if [[ -s check.tmp ]]; then
+            echo -e "\nDuplicates found:"
+            cat check.tmp
+
+            sort -u "${{ vars.RAW_FILE }}" -o "${{ vars.RAW_FILE }}"
+
+            echo
+            exit 1
+          fi
+
+      - name: Whitelisted TLDs check
+        if: success() || failure()
+        run: |
+          > check.tmp
+          grep -E '\.(gov|edu)(\.[a-z]{2})?$' "${{ vars.RAW_FILE }}" > check.tmp || true
+
+          if [[ -s check.tmp ]]; then
+            echo -e "\nDomains with whitelisted TLDs found:"
+            cat check.tmp
+
+            comm -23 "${{ vars.RAW_FILE }}" check.tmp > raw.tmp
+            mv raw.tmp "${{ vars.RAW_FILE }}"
+
+            echo
+            exit 1
+          fi
+
+      - name: Invalid domains check
+        if: success() || failure()
+        run: |
+          > check.tmp
+          grep -vE '^[[:alnum:].-]+\.[[:alnum:]-]{2,}$' "${{ vars.RAW_FILE }}" > check.tmp || true
+         
+          if [[ -s check.tmp ]]; then
+            echo -e "\nInvalid domains found:"
+            cat check.tmp
+
+            comm -23 "${{ vars.RAW_FILE }}" check.tmp > raw.tmp
+            mv raw.tmp "${{ vars.RAW_FILE }}"
+
+            echo
+            exit 1
+          fi
+
       - name: Build Domains list
+        if: success() || failure()
         run: bash "workflow_scripts/build_domains.sh"
 
       - name: Build Adblock Plus list
+        if: success() || failure()
         run: bash "workflow_scripts/build_adblock.sh"
 
       - name: Save changes
+        if: success() || failure()
         run: bash "workflow_scripts/save_changes.sh"
+
+
+      - name: Commit and push
+        if: success() || failure()
+        run: |
+          COMMIT_MSG='Remove invalid entries'
+          FILES_TO_ADD=( "${{ vars.RAW_FILE }}" )
+          git config user.email '${{ vars.GIT_EMAIL }}'
+          git config user.name '${{ vars.GIT_USERNAME }}'
+          git add "${FILES_TO_ADD[@]}"
+          git diff-index --quiet HEAD || git commit -m "$COMMIT_MSG"
+          git push
